# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mxmn_main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1249, 678)
        self.action_company_reg = QAction(MainWindow)
        self.action_company_reg.setObjectName(u"action_company_reg")
        self.action_company_reg.setMenuRole(QAction.MenuRole.NoRole)
        self.action2 = QAction(MainWindow)
        self.action2.setObjectName(u"action2")
        self.action2.setMenuRole(QAction.MenuRole.NoRole)
        self.action3 = QAction(MainWindow)
        self.action3.setObjectName(u"action3")
        self.action3.setMenuRole(QAction.MenuRole.NoRole)
        self.action4 = QAction(MainWindow)
        self.action4.setObjectName(u"action4")
        self.action4.setMenuRole(QAction.MenuRole.NoRole)
        self.action_shortcut = QAction(MainWindow)
        self.action_shortcut.setObjectName(u"action_shortcut")
        self.action_shortcut.setMenuRole(QAction.MenuRole.NoRole)
        self.action6 = QAction(MainWindow)
        self.action6.setObjectName(u"action6")
        self.action6.setMenuRole(QAction.MenuRole.NoRole)
        self.action7 = QAction(MainWindow)
        self.action7.setObjectName(u"action7")
        self.action7.setMenuRole(QAction.MenuRole.NoRole)
        self.action8 = QAction(MainWindow)
        self.action8.setObjectName(u"action8")
        self.action8.setMenuRole(QAction.MenuRole.NoRole)
        self.action_exit = QAction(MainWindow)
        self.action_exit.setObjectName(u"action_exit")
        self.action_exit.setMenuRole(QAction.MenuRole.NoRole)
        self.action2_2 = QAction(MainWindow)
        self.action2_2.setObjectName(u"action2_2")
        self.action3_2 = QAction(MainWindow)
        self.action3_2.setObjectName(u"action3_2")
        self.action4_iU = QAction(MainWindow)
        self.action4_iU.setObjectName(u"action4_iU")
        self.action1_3 = QAction(MainWindow)
        self.action1_3.setObjectName(u"action1_3")
        self.action2_3 = QAction(MainWindow)
        self.action2_3.setObjectName(u"action2_3")
        self.action1_4 = QAction(MainWindow)
        self.action1_4.setObjectName(u"action1_4")
        self.action2_4 = QAction(MainWindow)
        self.action2_4.setObjectName(u"action2_4")
        self.action3_3 = QAction(MainWindow)
        self.action3_3.setObjectName(u"action3_3")
        self.action4_2 = QAction(MainWindow)
        self.action4_2.setObjectName(u"action4_2")
        self.action5_2 = QAction(MainWindow)
        self.action5_2.setObjectName(u"action5_2")
        self.action6_2 = QAction(MainWindow)
        self.action6_2.setObjectName(u"action6_2")
        self.action7_2 = QAction(MainWindow)
        self.action7_2.setObjectName(u"action7_2")
        self.action8_2 = QAction(MainWindow)
        self.action8_2.setObjectName(u"action8_2")
        self.action9_2 = QAction(MainWindow)
        self.action9_2.setObjectName(u"action9_2")
        self.action10 = QAction(MainWindow)
        self.action10.setObjectName(u"action10")
        self.action11 = QAction(MainWindow)
        self.action11.setObjectName(u"action11")
        self.action1_5 = QAction(MainWindow)
        self.action1_5.setObjectName(u"action1_5")
        self.action2_5 = QAction(MainWindow)
        self.action2_5.setObjectName(u"action2_5")
        self.action3_4 = QAction(MainWindow)
        self.action3_4.setObjectName(u"action3_4")
        self.action4_3 = QAction(MainWindow)
        self.action4_3.setObjectName(u"action4_3")
        self.action5_3 = QAction(MainWindow)
        self.action5_3.setObjectName(u"action5_3")
        self.action1_6 = QAction(MainWindow)
        self.action1_6.setObjectName(u"action1_6")
        self.action2_6 = QAction(MainWindow)
        self.action2_6.setObjectName(u"action2_6")
        self.action3_5 = QAction(MainWindow)
        self.action3_5.setObjectName(u"action3_5")
        self.action4_4 = QAction(MainWindow)
        self.action4_4.setObjectName(u"action4_4")
        self.action1_7 = QAction(MainWindow)
        self.action1_7.setObjectName(u"action1_7")
        self.action2_7 = QAction(MainWindow)
        self.action2_7.setObjectName(u"action2_7")
        self.action3_6 = QAction(MainWindow)
        self.action3_6.setObjectName(u"action3_6")
        self.action4_5 = QAction(MainWindow)
        self.action4_5.setObjectName(u"action4_5")
        self.action5_4 = QAction(MainWindow)
        self.action5_4.setObjectName(u"action5_4")
        self.action6_3 = QAction(MainWindow)
        self.action6_3.setObjectName(u"action6_3")
        self.action7_3 = QAction(MainWindow)
        self.action7_3.setObjectName(u"action7_3")
        self.action8_3 = QAction(MainWindow)
        self.action8_3.setObjectName(u"action8_3")
        self.action9_3 = QAction(MainWindow)
        self.action9_3.setObjectName(u"action9_3")
        self.action10_DM = QAction(MainWindow)
        self.action10_DM.setObjectName(u"action10_DM")
        self.action11_2 = QAction(MainWindow)
        self.action11_2.setObjectName(u"action11_2")
        self.action12 = QAction(MainWindow)
        self.action12.setObjectName(u"action12")
        self.action13 = QAction(MainWindow)
        self.action13.setObjectName(u"action13")
        self.action14 = QAction(MainWindow)
        self.action14.setObjectName(u"action14")
        self.action15 = QAction(MainWindow)
        self.action15.setObjectName(u"action15")
        self.action16 = QAction(MainWindow)
        self.action16.setObjectName(u"action16")
        self.action17 = QAction(MainWindow)
        self.action17.setObjectName(u"action17")
        self.action18 = QAction(MainWindow)
        self.action18.setObjectName(u"action18")
        self.action19 = QAction(MainWindow)
        self.action19.setObjectName(u"action19")
        self.action20 = QAction(MainWindow)
        self.action20.setObjectName(u"action20")
        self.action21 = QAction(MainWindow)
        self.action21.setObjectName(u"action21")
        self.action22 = QAction(MainWindow)
        self.action22.setObjectName(u"action22")
        self.action1_8 = QAction(MainWindow)
        self.action1_8.setObjectName(u"action1_8")
        self.action2_8 = QAction(MainWindow)
        self.action2_8.setObjectName(u"action2_8")
        self.action3_7 = QAction(MainWindow)
        self.action3_7.setObjectName(u"action3_7")
        self.action4_6 = QAction(MainWindow)
        self.action4_6.setObjectName(u"action4_6")
        self.action5_5 = QAction(MainWindow)
        self.action5_5.setObjectName(u"action5_5")
        self.action6_4 = QAction(MainWindow)
        self.action6_4.setObjectName(u"action6_4")
        self.action7_4 = QAction(MainWindow)
        self.action7_4.setObjectName(u"action7_4")
        self.action1_9 = QAction(MainWindow)
        self.action1_9.setObjectName(u"action1_9")
        self.action2_9 = QAction(MainWindow)
        self.action2_9.setObjectName(u"action2_9")
        self.action3_8 = QAction(MainWindow)
        self.action3_8.setObjectName(u"action3_8")
        self.action4_7 = QAction(MainWindow)
        self.action4_7.setObjectName(u"action4_7")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1249, 33))
        self.menu1 = QMenu(self.menuBar)
        self.menu1.setObjectName(u"menu1")
        self.menu2 = QMenu(self.menuBar)
        self.menu2.setObjectName(u"menu2")
        self.menu1_2 = QMenu(self.menu2)
        self.menu1_2.setObjectName(u"menu1_2")
        self.menu3 = QMenu(self.menuBar)
        self.menu3.setObjectName(u"menu3")
        self.menu4 = QMenu(self.menuBar)
        self.menu4.setObjectName(u"menu4")
        self.menu5 = QMenu(self.menuBar)
        self.menu5.setObjectName(u"menu5")
        self.menu6 = QMenu(self.menuBar)
        self.menu6.setObjectName(u"menu6")
        self.menu7 = QMenu(self.menuBar)
        self.menu7.setObjectName(u"menu7")
        self.menu8 = QMenu(self.menuBar)
        self.menu8.setObjectName(u"menu8")
        self.menu9 = QMenu(self.menuBar)
        self.menu9.setObjectName(u"menu9")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.menuBar.addAction(self.menu1.menuAction())
        self.menuBar.addAction(self.menu2.menuAction())
        self.menuBar.addAction(self.menu3.menuAction())
        self.menuBar.addAction(self.menu4.menuAction())
        self.menuBar.addAction(self.menu5.menuAction())
        self.menuBar.addAction(self.menu6.menuAction())
        self.menuBar.addAction(self.menu7.menuAction())
        self.menuBar.addAction(self.menu8.menuAction())
        self.menuBar.addAction(self.menu9.menuAction())
        self.menu1.addAction(self.action_company_reg)
        self.menu1.addAction(self.action2)
        self.menu1.addAction(self.action3)
        self.menu1.addSeparator()
        self.menu1.addAction(self.action4)
        self.menu1.addAction(self.action_shortcut)
        self.menu1.addAction(self.action6)
        self.menu1.addAction(self.action7)
        self.menu1.addAction(self.action8)
        self.menu1.addSeparator()
        self.menu1.addAction(self.action_exit)
        self.menu2.addAction(self.menu1_2.menuAction())
        self.menu2.addAction(self.action2_2)
        self.menu2.addAction(self.action3_2)
        self.menu2.addAction(self.action4_iU)
        self.menu1_2.addAction(self.action1_9)
        self.menu1_2.addAction(self.action2_9)
        self.menu1_2.addAction(self.action3_8)
        self.menu1_2.addAction(self.action4_7)
        self.menu3.addAction(self.action1_3)
        self.menu3.addAction(self.action2_3)
        self.menu4.addAction(self.action1_4)
        self.menu4.addAction(self.action2_4)
        self.menu4.addAction(self.action3_3)
        self.menu4.addAction(self.action4_2)
        self.menu4.addAction(self.action5_2)
        self.menu4.addAction(self.action6_2)
        self.menu4.addAction(self.action7_2)
        self.menu4.addAction(self.action8_2)
        self.menu4.addAction(self.action9_2)
        self.menu4.addAction(self.action10)
        self.menu4.addAction(self.action11)
        self.menu5.addAction(self.action1_5)
        self.menu5.addAction(self.action2_5)
        self.menu5.addAction(self.action3_4)
        self.menu5.addAction(self.action4_3)
        self.menu5.addAction(self.action5_3)
        self.menu6.addAction(self.action1_6)
        self.menu6.addAction(self.action2_6)
        self.menu6.addAction(self.action3_5)
        self.menu6.addAction(self.action4_4)
        self.menu7.addAction(self.action1_7)
        self.menu7.addAction(self.action2_7)
        self.menu7.addAction(self.action3_6)
        self.menu7.addAction(self.action4_5)
        self.menu7.addAction(self.action5_4)
        self.menu7.addAction(self.action6_3)
        self.menu7.addAction(self.action7_3)
        self.menu7.addAction(self.action8_3)
        self.menu7.addAction(self.action9_3)
        self.menu7.addAction(self.action10_DM)
        self.menu7.addAction(self.action11_2)
        self.menu7.addAction(self.action12)
        self.menu7.addAction(self.action13)
        self.menu7.addAction(self.action14)
        self.menu7.addAction(self.action15)
        self.menu7.addAction(self.action16)
        self.menu7.addAction(self.action17)
        self.menu7.addAction(self.action18)
        self.menu7.addAction(self.action19)
        self.menu7.addAction(self.action20)
        self.menu7.addAction(self.action21)
        self.menu7.addAction(self.action22)
        self.menu8.addAction(self.action1_8)
        self.menu8.addAction(self.action2_8)
        self.menu8.addAction(self.action3_7)
        self.menu8.addAction(self.action4_6)
        self.menu8.addAction(self.action5_5)
        self.menu8.addAction(self.action6_4)
        self.menu8.addAction(self.action7_4)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_company_reg.setText(QCoreApplication.translate("MainWindow", u"1.\uc5c5\uccb4\ub4f1\ub85d", None))
        self.action_company_reg.setProperty(u"2.\ube44\ubc00\ubc88\ud638\ubcc0\uacbd", "")
        self.action2.setText(QCoreApplication.translate("MainWindow", u"2.\ube44\ubc00\ubc88\ud638\ubcc0\uacbd", None))
        self.action3.setText(QCoreApplication.translate("MainWindow", u"3.\ud504\ub9b0\ud130\uc124\uc815", None))
        self.action4.setText(QCoreApplication.translate("MainWindow", u"4.\uc6b0\ud3b8\ubc88\ud638\uc870\ud68c", None))
        self.action_shortcut.setText(QCoreApplication.translate("MainWindow", u"5.\ub2e8\ucd95\uba54\ub274", None))
        self.action6.setText(QCoreApplication.translate("MainWindow", u"6.\uc6d0\uaca9\uc9c0\uc6d0", None))
        self.action7.setText(QCoreApplication.translate("MainWindow", u"7.\ud658\uacbd\uc124\uc815", None))
        self.action8.setText(QCoreApplication.translate("MainWindow", u"8.\ubbf8\ud2b8\ud1b5\uc2e0 \uc5f4\uae30", None))
        self.action_exit.setText(QCoreApplication.translate("MainWindow", u"9.\uc885\ub8cc", None))
        self.action2_2.setText(QCoreApplication.translate("MainWindow", u"2.\ucf54\ub4dc\uad00\ub9ac", None))
        self.action3_2.setText(QCoreApplication.translate("MainWindow", u"3.\uac70\ub798\ucc98 \uae30\ucd08\uc794\uc561 \uc785\ub825", None))
        self.action4_iU.setText(QCoreApplication.translate("MainWindow", u"4.\ub354\uc874iU\uc5f0\ub3d9\uad00\ub9ac", None))
        self.action1_3.setText(QCoreApplication.translate("MainWindow", u"1.\uc624\ud37c\uad00\ub9ac", None))
        self.action2_3.setText(QCoreApplication.translate("MainWindow", u"2.\uc218\uc785\ubd80\ub300\ube44\uc6a9\uad00\ub9ac", None))
        self.action1_4.setText(QCoreApplication.translate("MainWindow", u"1.\uc785\uace0\uc804\ud45c(\uc9c1\uc218\uc785)", None))
        self.action2_4.setText(QCoreApplication.translate("MainWindow", u"2.\uc785\uace0\uc804\ud45c(\uad6d\ub0b4)", None))
        self.action3_3.setText(QCoreApplication.translate("MainWindow", u"3.\ucd9c\uace0\uc804\ud45c", None))
        self.action4_2.setText(QCoreApplication.translate("MainWindow", u"4.\ucc3d\uace0\uc774\ub3d9", None))
        self.action5_2.setText(QCoreApplication.translate("MainWindow", u"5.\ub85c\uc2a4\ucd9c\uace0", None))
        self.action6_2.setText(QCoreApplication.translate("MainWindow", u"6.\uc0dd\uc0b0\uc77c\ubcf4", None))
        self.action7_2.setText(QCoreApplication.translate("MainWindow", u"7.\uc9c0\uc721\uad6c\ub9e4\uc785\uace0/\ud310\ub9e4\ucd9c\uace0", None))
        self.action8_2.setText(QCoreApplication.translate("MainWindow", u"8.\uc9c0\uc721\uc0dd\uc0b0\uc785\uace0", None))
        self.action9_2.setText(QCoreApplication.translate("MainWindow", u"9.\uac70\ub798\ucc98 \uc790\ub8cc \uc77c\uad04\uc804\ud658", None))
        self.action10.setText(QCoreApplication.translate("MainWindow", u"10.\uacac\uc801\uc11c", None))
        self.action11.setText(QCoreApplication.translate("MainWindow", u"11.\uc0dd\uc0b0 \uac00\uacf5\uacc4\ud68d", None))
        self.action1_5.setText(QCoreApplication.translate("MainWindow", u"1.\uc785\uae08(\ubbf8\uc218\uae08)\uad00\ub9ac", None))
        self.action2_5.setText(QCoreApplication.translate("MainWindow", u"2.\ucd9c\uae08(\ubbf8\uc9c0\uae09)\uad00\ub9ac", None))
        self.action3_4.setText(QCoreApplication.translate("MainWindow", u"3.\uc785\uae08(\uacbd\ube44)\uad00\ub9ac", None))
        self.action4_3.setText(QCoreApplication.translate("MainWindow", u"4.\ucd9c\uae08(\uacbd\ube44)\uad00\ub9ac", None))
        self.action5_3.setText(QCoreApplication.translate("MainWindow", u"5.\ud1b5\uc7a5\uc774\uccb4", None))
        self.action1_6.setText(QCoreApplication.translate("MainWindow", u"1.\uc7ac\uace0\ub9c8\uac10\uad00\ub9ac", None))
        self.action2_6.setText(QCoreApplication.translate("MainWindow", u"2.\uc77c\ub9c8\uac10", None))
        self.action3_5.setText(QCoreApplication.translate("MainWindow", u"3.\ub354\uc874\uc5f0\ub3d9", None))
        self.action4_4.setText(QCoreApplication.translate("MainWindow", u"4.\ub9e4\ucd9c\uc774\uc775\uc815\uc0b0", None))
        self.action1_7.setText(QCoreApplication.translate("MainWindow", u"1.\ucf54\ub4dc\ud604\ud669", None))
        self.action2_7.setText(QCoreApplication.translate("MainWindow", u"2.\ub9e4\uc785\ud604\ud669", None))
        self.action3_6.setText(QCoreApplication.translate("MainWindow", u"3.\ud310\ub9e4\ud604\ud669", None))
        self.action4_5.setText(QCoreApplication.translate("MainWindow", u"4.\uc6d0\uc7a5\ucd9c\ub825", None))
        self.action5_4.setText(QCoreApplication.translate("MainWindow", u"5.\uc77c\uacc4\ud45c", None))
        self.action6_3.setText(QCoreApplication.translate("MainWindow", u"6.\ub9e4\ucd9c\uc774\uc775", None))
        self.action7_3.setText(QCoreApplication.translate("MainWindow", u"7.\uc785\ucd9c\uae08\ud604\ud669", None))
        self.action8_3.setText(QCoreApplication.translate("MainWindow", u"8.\ubbf8\uc218/\ubbf8\uc9c0\uae09\ud604\ud669", None))
        self.action9_3.setText(QCoreApplication.translate("MainWindow", u"9.\uc0c1\ud488\uc7ac\uace0\ud604\ud669", None))
        self.action10_DM.setText(QCoreApplication.translate("MainWindow", u"10.DM\ubc1c\uc1a1", None))
        self.action11_2.setText(QCoreApplication.translate("MainWindow", u"11.\uc190\uc775\uacc4\uc0b0\uc11c", None))
        self.action12.setText(QCoreApplication.translate("MainWindow", u"12.\uc794\uc561\ud655\uc778\uc11c", None))
        self.action13.setText(QCoreApplication.translate("MainWindow", u"13.\uac70\ub798\ub9e4\uc5ed \ud655\uc778\uc11c(\uc6d4\ubcc4)", None))
        self.action14.setText(QCoreApplication.translate("MainWindow", u"14.\ud1b5\uc7a5\uad00\ub9ac", None))
        self.action15.setText(QCoreApplication.translate("MainWindow", u"15.\uacbd\ub9ac\uc77c\ubcf4", None))
        self.action16.setText(QCoreApplication.translate("MainWindow", u"16.\uc790\uc0b0\ud604\ud669", None))
        self.action17.setText(QCoreApplication.translate("MainWindow", u"17.\uac70\ub798\ub0b4\uc5ed\uc11c", None))
        self.action18.setText(QCoreApplication.translate("MainWindow", u"18.\uc0dd\uc0b0\ud604\ud669", None))
        self.action19.setText(QCoreApplication.translate("MainWindow", u"19.\uac70\ub798\uba85\uc138\ud45c\ucd9c\ub825(\uc77c\uad04)", None))
        self.action20.setText(QCoreApplication.translate("MainWindow", u"20.\uc0dd\uc0b0\ub77c\ubca8\ud604\ud669", None))
        self.action21.setText(QCoreApplication.translate("MainWindow", u"21.\uc77c\uc77c\ubcf4\uace0", None))
        self.action22.setText(QCoreApplication.translate("MainWindow", u"22.\ubc14\ucf54\ub4dc\ud604\ud669", None))
        self.action1_8.setText(QCoreApplication.translate("MainWindow", u"1.\uacc4\uc0b0\uc11c\uc791\uc5c5", None))
        self.action2_8.setText(QCoreApplication.translate("MainWindow", u"2.\uacc4\uc0b0\uc11c\uc785\ub825", None))
        self.action3_7.setText(QCoreApplication.translate("MainWindow", u"3.\uacc4\uc0b0\uc11c\ud604\ud669", None))
        self.action4_6.setText(QCoreApplication.translate("MainWindow", u"4.\uacc4\uc0b0\uc11c\ucd9c\ub825(\uc77c\uad04)", None))
        self.action5_5.setText(QCoreApplication.translate("MainWindow", u"5.\uacc4\uc0b0\uc11c\uc0ad\uc81c", None))
        self.action6_4.setText(QCoreApplication.translate("MainWindow", u"6.\uac70\ub798\uc0ac\uc2e4\ud655\uc778\uc11c", None))
        self.action7_4.setText(QCoreApplication.translate("MainWindow", u"7.\uc804\uc790\uacc4\uc0b0\uc11c", None))
        self.action1_9.setText(QCoreApplication.translate("MainWindow", u"1.\uc0ac\uc6a9\uc790\ub4f1\ub85d", None))
        self.action2_9.setText(QCoreApplication.translate("MainWindow", u"2.\uc0ac\uc6a9\uc790\ubcc4 \ud504\ub85c\uadf8\ub7a8 \uad8c\ud55c", None))
        self.action3_8.setText(QCoreApplication.translate("MainWindow", u"3.\uc804\uc790\uacc4\uc0b0\uc11c\uc0ac\uc6a9\uc790\ub4f1\ub85d", None))
        self.action4_7.setText(QCoreApplication.translate("MainWindow", u"4.\uc0ac\uc6a9\uc790 \uc811\uc18d\ud604\ud669", None))
        self.menu1.setTitle(QCoreApplication.translate("MainWindow", u"1.\uc2dc\uc2a4\ud15c\uad00\ub9ac", None))
        self.menu2.setTitle(QCoreApplication.translate("MainWindow", u"2.\ucf54\ub4dc\uad00\ub9ac", None))
        self.menu1_2.setTitle(QCoreApplication.translate("MainWindow", u"1.\uc0ac\uc6a9\uc790\uad00\ub9ac", None))
        self.menu3.setTitle(QCoreApplication.translate("MainWindow", u"3.\uc218\uc785\uad00\ub9ac", None))
        self.menu4.setTitle(QCoreApplication.translate("MainWindow", u"4.\uc0c1\ud488\uc785/\ucd9c\uace0\uad00\ub9ac", None))
        self.menu5.setTitle(QCoreApplication.translate("MainWindow", u"5.\uc785\uae08/\ucd9c\uae08\uad00\ub9ac", None))
        self.menu6.setTitle(QCoreApplication.translate("MainWindow", u"6.\uc6d4\uc7ac\uace0\ub9c8\uac10\uad00\ub9ac", None))
        self.menu7.setTitle(QCoreApplication.translate("MainWindow", u"7.\uc870\ud68c/\ucd9c\ub825", None))
        self.menu8.setTitle(QCoreApplication.translate("MainWindow", u"8.\uacc4\uc0b0\uc11c\uad00\ub9ac", None))
        self.menu9.setTitle(QCoreApplication.translate("MainWindow", u"9.\ud30c\uc774\ub0b8\uc2f1/\uacc4\uc57d\ud310\ub9e4", None))
    # retranslateUi

