"""일반 매출/출고 Vertical Slice Migration (재실행 안전, 실행 전 DB 대상 확인 필수)."""
from sqlalchemy import text
from database import engine

def migrate():
    with engine.begin() as conn:
        target = conn.execute(text("SELECT @@SERVERNAME AS server_name, DB_NAME() AS database_name")).mappings().one()
        print(f"Target: {target['server_name']} / {target['database_name']}")
        conn.execute(text("""
        IF OBJECT_ID('dbo.tb_sale','U') IS NULL CREATE TABLE dbo.tb_sale (
          sale_id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_sale PRIMARY KEY, comp_code VARCHAR(10) NOT NULL, sale_no VARCHAR(30) NOT NULL, sale_date DATE NOT NULL, account_id INT NOT NULL, document_status VARCHAR(20) NOT NULL CONSTRAINT DF_sale_status DEFAULT 'DRAFT', total_box_qty INT NOT NULL DEFAULT 0, total_weight NUMERIC(18,2) NOT NULL DEFAULT 0, total_supply_amount NUMERIC(18,0) NOT NULL DEFAULT 0, total_tax_amount NUMERIC(18,0) NOT NULL DEFAULT 0, total_discount_amount NUMERIC(18,0) NOT NULL DEFAULT 0, total_amount NUMERIC(18,0) NOT NULL DEFAULT 0, memo NVARCHAR(1000) NULL, inventory_exception_yn BIT NOT NULL DEFAULT 0, inventory_exception_reason NVARCHAR(1000) NULL, created_by VARCHAR(50) NOT NULL, created_at DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(), updated_by VARCHAR(50) NOT NULL, updated_at DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(), confirmed_by VARCHAR(50) NULL, confirmed_at DATETIMEOFFSET NULL, cancelled_by VARCHAR(50) NULL, cancelled_at DATETIMEOFFSET NULL,
          CONSTRAINT UQ_sale_company_no UNIQUE(comp_code,sale_no), CONSTRAINT FK_sale_company FOREIGN KEY(comp_code) REFERENCES dbo.tb_company(comp_code), CONSTRAINT FK_sale_account FOREIGN KEY(account_id) REFERENCES dbo.tb_account(account_id), CONSTRAINT FK_sale_created FOREIGN KEY(created_by) REFERENCES dbo.tb_user(user_id), CONSTRAINT FK_sale_updated FOREIGN KEY(updated_by) REFERENCES dbo.tb_user(user_id), CONSTRAINT FK_sale_confirmed FOREIGN KEY(confirmed_by) REFERENCES dbo.tb_user(user_id), CONSTRAINT FK_sale_cancelled FOREIGN KEY(cancelled_by) REFERENCES dbo.tb_user(user_id), CONSTRAINT CK_sale_status CHECK(document_status IN ('DRAFT','CONFIRMED','CANCELLED')));
        IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_sale_lookup' AND object_id=OBJECT_ID('dbo.tb_sale')) CREATE INDEX IX_sale_lookup ON dbo.tb_sale(comp_code,sale_date,document_status);
        IF OBJECT_ID('dbo.tb_sale_item','U') IS NULL CREATE TABLE dbo.tb_sale_item (
          sale_item_id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_sale_item PRIMARY KEY, sale_id INT NOT NULL, line_no INT NOT NULL, product_id INT NOT NULL, lot_id INT NOT NULL, box_qty INT NOT NULL, weight NUMERIC(18,2) NOT NULL, unit_price NUMERIC(18,0) NOT NULL, supply_amount NUMERIC(18,0) NOT NULL, tax_code_snapshot VARCHAR(20) NOT NULL, tax_name_snapshot NVARCHAR(100) NOT NULL, tax_rate_snapshot NUMERIC(5,2) NOT NULL, tax_amount NUMERIC(18,0) NOT NULL, discount_amount NUMERIC(18,0) NOT NULL DEFAULT 0, total_amount NUMERIC(18,0) NOT NULL, memo NVARCHAR(500) NULL, CONSTRAINT UQ_sale_item_line UNIQUE(sale_id,line_no), CONSTRAINT FK_sale_item_sale FOREIGN KEY(sale_id) REFERENCES dbo.tb_sale(sale_id), CONSTRAINT FK_sale_item_product FOREIGN KEY(product_id) REFERENCES dbo.tb_product(product_id), CONSTRAINT FK_sale_item_lot FOREIGN KEY(lot_id) REFERENCES dbo.tb_lot(lot_id));
        IF OBJECT_ID('dbo.tb_outbound','U') IS NULL CREATE TABLE dbo.tb_outbound (
          outbound_id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_outbound PRIMARY KEY, comp_code VARCHAR(10) NOT NULL, outbound_no VARCHAR(30) NOT NULL, outbound_date DATE NOT NULL, warehouse_id INT NOT NULL, transaction_type VARCHAR(30) NOT NULL, memo NVARCHAR(1000) NULL, created_at DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(), CONSTRAINT UQ_outbound_company_no UNIQUE(comp_code,outbound_no), CONSTRAINT FK_outbound_company FOREIGN KEY(comp_code) REFERENCES dbo.tb_company(comp_code), CONSTRAINT FK_outbound_warehouse FOREIGN KEY(warehouse_id) REFERENCES dbo.tb_warehouse(warehouse_id));
        IF OBJECT_ID('dbo.tb_outbound_item','U') IS NULL CREATE TABLE dbo.tb_outbound_item (
          outbound_item_id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_outbound_item PRIMARY KEY, outbound_id INT NOT NULL, sale_item_id INT NOT NULL, line_no INT NOT NULL, product_id INT NOT NULL, lot_id INT NOT NULL, box_qty INT NOT NULL, weight NUMERIC(18,2) NOT NULL, amount NUMERIC(18,0) NOT NULL, CONSTRAINT UQ_outbound_item_line UNIQUE(outbound_id,line_no), CONSTRAINT FK_outbound_item_header FOREIGN KEY(outbound_id) REFERENCES dbo.tb_outbound(outbound_id), CONSTRAINT FK_outbound_item_sale FOREIGN KEY(sale_item_id) REFERENCES dbo.tb_sale_item(sale_item_id), CONSTRAINT FK_outbound_item_product FOREIGN KEY(product_id) REFERENCES dbo.tb_product(product_id), CONSTRAINT FK_outbound_item_lot FOREIGN KEY(lot_id) REFERENCES dbo.tb_lot(lot_id));
        """))
        conn.execute(text("""
        IF EXISTS(SELECT 1 FROM sys.check_constraints WHERE name='CK_account_tx_type') ALTER TABLE dbo.tb_account_transaction DROP CONSTRAINT CK_account_tx_type;
        ALTER TABLE dbo.tb_account_transaction ADD CONSTRAINT CK_account_tx_type CHECK(transaction_type IN ('OPENING_RECEIVABLE','OPENING_PAYABLE','PURCHASE_PAYABLE','SALES_RECEIVABLE','RECEIPT','PAYMENT'));
        IF EXISTS(SELECT 1 FROM dbo.tb_menu_master WHERE menu_code='SALES_GENERAL') UPDATE dbo.tb_menu_master SET menu_name=N'상품매출/출고등록',menu_group=N'상품입/출고관리',sort_order=220,use_yn=1 WHERE menu_code='SALES_GENERAL'; ELSE INSERT dbo.tb_menu_master(menu_code,menu_name,menu_group,sort_order,use_yn) VALUES('SALES_GENERAL',N'상품매출/출고등록',N'상품입/출고관리',220,1);
        INSERT dbo.tb_user_menu_permission(user_id,menu_code,can_read,can_create,can_update,can_delete) SELECT user_id,'SALES_GENERAL',1,1,1,1 FROM dbo.tb_user u WHERE u.is_admin=1 AND NOT EXISTS(SELECT 1 FROM dbo.tb_user_menu_permission p WHERE p.user_id=u.user_id AND p.menu_code='SALES_GENERAL');
        """))
    print("General sales/outbound migration completed.")

if __name__ == '__main__': migrate()
